spring:
  application:
    name: last-drop-v2

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/last_drop
    username: localdbuser
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-xlbubx8zg3c4dpjs.us.auth0.com/.well-known/jwks.json