name: Label new issues

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check issue title
        id: check_title
        run: |
          if [[ "${{ github.event.issue.title }}" == Recipe:* ]]; then
            echo "##[set-output name=add_label;]true"
          else
            echo "##[set-output name=add_label;]false"
          fi
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        if: steps.check_title.outputs.add_label == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: recipe